<?php
// database/seeders/EstadisticaJugadorSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EstadisticaJugador;

class EstadisticaJugadorSeeder extends Seeder
{
    public function run()
    {
        $datos = [
            [
                'id_jugador' => 1,
                'id_equipo' => 11,
                'id_calendario' => 1,
                'id_temporadacompetencia' => 6,
                'posicion' => 'Delantero',
                'nombre' => 'Robert Lewandowski',
                'calificacion' => 8.5,
                'goles' => 2,
                'asistencias' => 1,
                'tiros' => 5,
                'precision_tiros' => 60,
                'pases' => 25,
                'precision_pases' => 85,
                'regates' => 3,
                'tasa_exito_entradas' => 70,
                'fueras_de_juego' => 0,
                'faltas_cometidas' => 1,
                'posesion_ganada' => 5,
                'posesion_perdida' => 2,
                'minutos_jugados_vs_equipo' => 90,
                'distancia_total_vs_equipo' => 10500,
                'distancia_carrera_vs_equipo' => 9000,
                'procesado' => true,
                'foto' => null,
            ],
            [
                'id_jugador' => 2,
                'id_equipo' => 21,
                'id_calendario' => 2,
                'id_temporadacompetencia' => 6,
                'posicion' => 'Mediocampista',
                'nombre' => 'Jude Bellingham',
                'calificacion' => 7.8,
                'goles' => 0,
                'asistencias' => 2,
                'tiros' => 3,
                'precision_tiros' => 33,
                'pases' => 40,
                'precision_pases' => 90,
                'regates' => 4,
                'tasa_exito_entradas' => 65,
                'fueras_de_juego' => 1,
                'faltas_cometidas' => 2,
                'posesion_ganada' => 6,
                'posesion_perdida' => 3,
                'minutos_jugados_vs_equipo' => 85,
                'distancia_total_vs_equipo' => 11000,
                'distancia_carrera_vs_equipo' => 9200,
                'procesado' => true,
                'foto' => null,
            ],
            [
                'id_jugador' => 3,
                'id_equipo' => 16,
                'id_calendario' => 3,
                'id_temporadacompetencia' => 6,
                'posicion' => 'Defensor',
                'nombre' => 'David Alaba',
                'calificacion' => 7.5,
                'goles' => 0,
                'asistencias' => 0,
                'tiros' => 1,
                'precision_tiros' => 100,
                'pases' => 50,
                'precision_pases' => 92,
                'regates' => 1,
                'tasa_exito_entradas' => 80,
                'fueras_de_juego' => 0,
                'faltas_cometidas' => 0,
                'posesion_ganada' => 7,
                'posesion_perdida' => 1,
                'minutos_jugados_vs_equipo' => 90,
                'distancia_total_vs_equipo' => 10200,
                'distancia_carrera_vs_equipo' => 8500,
                'procesado' => true,
                'foto' => null,
            ],
            [
                'id_jugador' => 4,
                'id_equipo' => 11,
                'id_calendario' => 1,
                'id_temporadacompetencia' => 6,
                'posicion' => 'Portero',
                'nombre' => 'Manuel Neuer',
                'calificacion' => 8.0,
                'goles' => 0,
                'asistencias' => 0,
                'tiros' => 0,
                'precision_tiros' => 0,
                'pases' => 15,
                'precision_pases' => 80,
                'regates' => 0,
                'tasa_exito_entradas' => 90,
                'fueras_de_juego' => 0,
                'faltas_cometidas' => 0,
                'posesion_ganada' => 10,
                'posesion_perdida' => 1,
                'minutos_jugados_vs_equipo' => 90,
                'distancia_total_vs_equipo' => 3000,
                'distancia_carrera_vs_equipo' => 2800,
                'procesado' => true,
                'foto' => null,
            ],
            [
                'id_jugador' => 5,
                'id_equipo' => 8,
                'id_calendario' => 4,
                'id_temporadacompetencia' => 6,
                'posicion' => 'Delantero',
                'nombre' => 'Erling Haaland',
                'calificacion' => 9.0,
                'goles' => 3,
                'asistencias' => 0,
                'tiros' => 7,
                'precision_tiros' => 70,
                'pases' => 20,
                'precision_pases' => 78,
                'regates' => 5,
                'tasa_exito_entradas' => 60,
                'fueras_de_juego' => 1,
                'faltas_cometidas' => 1,
                'posesion_ganada' => 4,
                'posesion_perdida' => 3,
                'minutos_jugados_vs_equipo' => 90,
                'distancia_total_vs_equipo' => 10700,
                'distancia_carrera_vs_equipo' => 9000,
                'procesado' => true,
                'foto' => null,
            ],
            // Puedes seguir agregando más entradas aquí para pruebas...
        ];

        foreach ($datos as $dato) {
            EstadisticaJugador::updateOrCreate(
                [
                    'id_jugador' => $dato['id_jugador'],
                    'id_calendario' => $dato['id_calendario'],
                ],
                $dato
            );
        }
    }
}
